---
version: '3'
services:
    dnsmasq:
        container_name: dnsmasq
        image: jpillora/dnsmasq
        ports:
          - "127.0.0.2:53:53/udp"
        volumes:
            - ./dnsmasq.conf:/etc/dnsmasq.conf

    web:
        container_name: web
        image: nginx:latest
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ..:/var/www/
        labels:
          traefik.enable: "true"
          traefik.http.routers.web.entrypoints: "web"
          traefik.http.routers.web.rule: "HostRegexp(`{subdomain:[a-z.-]+}.php{version:[0-9]+}.loc`)"
          traefik.http.services.web.loadbalancer.server.port: "80"

    php-74:
        container_name: php74
        build:
          context: .
          dockerfile: php.dockerfile
          args:
              BASE_IMAGE: "php:7.4-fpm"
        volumes:
            - ..:/var/www/
            - ./supervisor:/etc/supervisor/conf.d

    php-80:
        container_name: php80
        build:
          context: .
          dockerfile: php.dockerfile
          args:
              BASE_IMAGE: "php:8.0-fpm"
        volumes:
            - ..:/var/www/
            - ./supervisor:/etc/supervisor/conf.d

    php-81:
        container_name: php81
        build:
          context: .
          dockerfile: php.dockerfile
          args:
              BASE_IMAGE: "php:8.1-fpm"
        volumes:
            - ..:/var/www/
            - ./supervisor:/etc/supervisor/conf.d

    redis:
        container_name: redis
        image: redis

    mysql:
        container_name: mysql
        image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    mailhog:
      container_name: mailhog
      image: mailhog/mailhog:latest
      logging:
          driver: 'none'
      ports:
          - 1025:1025
          - 8025:8025

volumes:
  mysql_data:

networks:
  default:
    external:
      name: user-bridge
